### PR TITLE
Move docker image to alpine

### PR DESCRIPTION
**Pull request by cryptiklemur**
Will significantly shrink the image size, solves #7

### CODE REVIEW

**Comment by cryptiklemur** [comment]
Hm, nio4r (required by puma) doesnt seem to work out of the box with alpine. Closing until I resolve that

**Comment by cryptiklemur** [comment]
Should be good now

**Comment by cryptiklemur** [comment]
Final image size looks to be 323001244 bytes (323mb), which looks to be about a third the size

**Comment by axsuul** [comment]
Thanks! Any reason why `CMD bundle exec puma --port $PORT` was removed?

**Comment by axsuul** [comment]
Bumping

**Comment by axsuul** [comment]
Closing in favor of #14

**Pull request closed without merging**
